/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/oNtCcPPQYcx
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/

/** Add border radius CSS variable to your global CSS:

:root {
  --radius: 0.75rem;
}
**/
import { CardTitle, CardDescription, CardHeader, CardContent, CardFooter, Card } from "@/components/ui/card"
import { ResponsiveBar } from "@nivo/bar"

export function Barchart() {
  return (
    <Card className="h-full w-full max-w-2xl">
      <CardHeader>
        <CardTitle>Sales by Product</CardTitle>
        <CardDescription>A horizontal bar chart showing total sales for each product.</CardDescription>
      </CardHeader>
      <CardContent>
        <HorizontalbarChart className="aspect-[16/9]" />
      </CardContent>
      <CardFooter className="flex items-center justify-between">
        <div className="flex items-center gap-4">
          <div className="h-3 w-3 rounded-full bg-[#6366F1]" />
          <span className="text-sm text-gray-500 dark:text-gray-400">Product A</span>
          <div className="h-3 w-3 rounded-full bg-[#10B981]" />
          <span className="text-sm text-gray-500 dark:text-gray-400">Product B</span>
          <div className="h-3 w-3 rounded-full bg-[#EF4444]" />
          <span className="text-sm text-gray-500 dark:text-gray-400">Product C</span>
        </div>
      </CardFooter>
    </Card>
  )
}

function HorizontalbarChart(props) {
  return (
    <div {...props}>
      <ResponsiveBar
        data={[
          { name: "Jan", desktop: 111, mobile: 99 },
          { name: "Feb", desktop: 157, mobile: 87 },
          { name: "Mar", desktop: 129, mobile: 89 },
          { name: "Apr", desktop: 187, mobile: 151 },
          { name: "May", desktop: 119, mobile: 127 },
          { name: "Jun", desktop: 20, mobile: 121 },
        ]}
        keys={["desktop", "mobile"]}
        indexBy="name"
        layout="horizontal"
        margin={{ top: 0, right: 0, bottom: 40, left: 40 }}
        padding={0.3}
        colors={["#2563eb", "#e11d48"]}
        axisBottom={{
          tickSize: 0,
          tickPadding: 8,
        }}
        axisLeft={{
          tickSize: 0,
          tickValues: 4,
          tickPadding: 16,
        }}
        gridYValues={4}
        theme={{
          tooltip: {
            chip: {
              borderRadius: "9999px",
            },
            container: {
              fontSize: "12px",
              textTransform: "capitalize",
              borderRadius: "6px",
            },
          },
          grid: {
            line: {
              stroke: "#f3f4f6",
            },
          },
        }}
        tooltipLabel={({ id }) => `${id}`}
        enableLabel={false}
        role="application"
        ariaLabel="A horizontal bar chart"
      />
    </div>
  )
}
